大写改为小写

diff --git a/bin/docker-addhost b/bin/docker-addhost
--- a/bin/docker-addhost
+++ b/bin/docker-addhost
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
 if [ $# -ne 2 ];then
-        echo "Usage : `basename $0` somehost.com /you/app/path"
-        exit 4
+    echo "Usage : `basename $0` somehost.com /you/app/path"
+    exit 4
 fi
 
 # if  [ ! -d $2 ] ;then
@@ -14,12 +14,12 @@ echo "127.0.0.1       $1" >> /etc/hosts
 
 echo "$1 host add to /etc/hosts successful!"
 
-touch "${HOME}/Docker/nginx/${1}.conf"
+touch "${HOME}/docker/nginx/${1}.conf"
 
-cat $HOME/Docker/nginx/template.conf | sed s@template.com@"$1"@ |sed s@/php/template@"/home/data/www/$2"@ > $HOME/Docker/nginx/${1}.conf
+cat $HOME/docker/nginx/template.conf | sed s@template.com@"$1"@ |sed s@/php/template@"/home/data/www/$2"@ > $HOME/docker/nginx/${1}.conf
 if [ $? -eq 0 ];then
-	$HOME/Docker/bin/docker-nginx
-        echo -e "touch ${1}.conf successful!\nnginx reload successfal!"
+	$HOME/docker/bin/docker-nginx
+    echo -e "touch ${1}.conf successful!\nnginx reload successfal!"
 else
-        echo "can't touch ${1}.conf"
+    echo "can't touch ${1}.conf"
 fi
